### ISSUE TITLE
往左旋转，出现一些莫名bug

### ISSUE THREAD

**Issue by xuehuashi** [1993hzw/Doodle#10]
往左旋转，我只把旋转的方法由+90度，改为-90，旋转后图片出现先放大后缩小，一闪，左右没有铺满，双指上划图片消失，涂鸦图片乱跑。。。莫名的问题，基本没改作者代码

**Comment by 1993hzw** [comment]
兄弟，灵活点．如果往右为+9０度，　而不支持-90度表示往左，那么为什么不用360-90=+270度，即往右+270度来达到跟往左-90度一样的效果呢？

**Comment by xuehuashi** [comment]
多谢了 ！ (mDoodle.getDoodleRotation() + 270) - 360完美左转
