### ISSUE TITLE
serializable

### ISSUE THREAD

**Issue by samanaslani1992** [1993hzw/Doodle#13]
hi
How get doodleView.getAllItem(); list as serializable?

**Comment by samanaslani1992** [comment]
`try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
             ObjectOutputStream oos = new ObjectOutputStream(baos)) {
            oos.writeObject(doodleView.getAllItem());
            bytes = baos.toByteArray();
        } catch (IOException e) {
            // Error in serialization
            e.printStackTrace();
      }`

**Comment by 1993hzw** [comment]
You must serialize all objects of IDoodleItem before persistent preservation. All member variables of IDoodleItem must be serizaliable, such as Path.  You can see this [how to serialize an object of android.graphics.Path](https://stackoverflow.com/questions/4919740/how-to-serialize-an-object-of-android-graphics-path)

**Comment by samanaslani1992** [comment]
thanks

**Comment by 1993hzw** [comment]
By the way, Doodle has upgraded from 5.3 to 5.4.
