### ISSUE TITLE
楼主毛笔效果怎么做呀

### ISSUE THREAD

**Issue by tiexuelinglongnv** [1993hzw/Doodle#14]

**Comment by xyh12344** [comment]
怎么做是一个宏观的问法？一般人没法回答的，你可以试试：我想怎么怎么做，然后通过怎么怎么做，最后遇到了什么问题，这个有什么好的办法？，这种问法好一点

**Comment by 1993hzw** [comment]
> 怎么做是一个宏观的问法？一般人没法回答的，你可以试试：我想怎么怎么做，然后通过怎么怎么做，最后遇到了什么问题，这个有什么好的办法？，这种问法好一点

兄弟说得不错，赞一个！
