### ISSUE TITLE
请问橡皮擦画笔如何使用

### ISSUE THREAD

**Issue by saltwater2233** [1993hzw/Doodle#16]
感谢你的优秀项目，我有几个疑问想请教：
1. 请问橡皮擦画笔如何使用？
直接设置doodleView.setPen(DoodlePen.ERASER)不起效果，
然后参考了MosaicDemo的马赛克画笔，发现需要使用doodleView.setColor()才行。
我尝试doodleView.setColor(null)但是crash了，不知道橡皮擦是否需要调用这个方法，参数该如何设置。

2. 如何使图片和View一样大？
我想图片拉伸成和手机屏幕一样的大小，就像ImageView的scaleType设置为fitXY

**Comment by 1993hzw** [comment]
1.
橡皮擦和仿制的原理是使用原图作为画笔的底图，因此需要设置`setColor(new DoodleColor(doodle.getBitmap()));`．
不过经过的提示，我做了优化，直接在相应的画笔内部做了优化，不需要额外调用setcolor了．最新版本为v5.4.0.2

2.
[你可以参考代码](https://github.com/1993hzw/Doodle/blob/master/extend.md)
