### ISSUE TITLE
请问多选如何实现

### ISSUE THREAD

**Issue by wangyutao** [1993hzw/Doodle#17]
手指画一个区域，把这个区域内的对象全部选中，可以做移动或者缩放操作，请问支持吗？或者如何扩展，请大神指导，多谢

**Comment by 1993hzw** [comment]
`DoodleOnTouchGestureListener`可以参考这个类的实现，这里面包含单选，理解逻辑后，多选其实也差不多原理．
最后自己自定义个手势识别器传给Doodle框架.
`// create touch detector, which dectects the gesture of scoll, scale, single tap, etc.
// 创建手势识别器，识别滚动，缩放，点击等手势
IDoodleTouchDetector detector = new DoodleTouchDetector(getApplicationContext(), mTouchGestureListener);
mDoodleView.setDefaultTouchDetector(detector);`
