### ISSUE TITLE
提一个建议：增加一些适合于移动设备的交互形式。

### ISSUE THREAD

**Issue by didikee** [1993hzw/Doodle#18]
比如：
添加一个图形，可以直接对图形进行按住移动，拖动缩放旋转等。（市场上大部分的图片编辑app都是这样的交互逻辑，感觉比较好）

我看作者更新了很久，确实写了很多值得学习的代码。希望在交互上优化下，让这个项目更上一层楼。
现在看起来比较适合鼠标操作。

ps：也可能是我个人感觉问题😊
很棒的项目，已经关注了。

**Comment by 1993hzw** [comment]
这些可以自定义呀　都是可拓展的
