### ISSUE TITLE
文档写错了吧

### ISSUE THREAD

**Issue by qq2956218657** [1993hzw/Doodle#24]
DoodleView mDoodleView = new DoodleView(this, bitmap, optimizeDrawing, new IDoodleListener() 
参数写错了。

**Comment by roybill** [comment]
确实是参数写错了,我现在改成正确的参数还是有问题,你的可以正常使用吗?

**Comment by qq2956218657** [comment]
> 确实是参数写错了,我现在改成正确的参数还是有问题,你的可以正常使用吗?

很久之前解决了，可以用。
