### ISSUE TITLE
同样的涂鸦，保存涂鸦图片在不同设备上生成的图片大小差别很大

### ISSUE THREAD

**Issue by xuehuashi** [1993hzw/Doodle#25]
红米5plus  生成涂鸦后图片变化很小，只比原图增大几十k, 但是在一加的一款，同样的涂鸦生成图片翻倍了，多次涂鸦出现300k -600k-1.2m-2.4m, 其他测试机单次涂鸦会出现不同大小的增大，多次涂鸦每次增幅基本相同，测试后发现图片放大后生成的图片尺寸和手机屏一致，生成涂鸦后bitmap，和手机屏幕分辨率有关？？

**Comment by 1993hzw** [comment]
ImageUtils.createBitmapFromPath 可以看下bitmap是怎么生成的 里面有取当前设备的大小去缩放图片
