### ISSUE TITLE
Android8.0设备上图片旋转后继续涂鸦卡顿

### ISSUE THREAD

**Issue by ReisenZ** [1993hzw/Doodle#3]
DoodelViewWrapper直接加载大尺寸Bitmap时(1920*1200), 旋转奇数次时涂鸦会非常卡, 偶数次时则不会.
查看log发现在DoodleView.doDraw(Canvas canvas)的
```Java
// 绘制涂鸦后的图片
canvas.drawBitmap(mDoodleBitmap, 0, 0, null);
```
位置耗费很多时间

该问题目前只在8.0设备上能复现, 8.1则没有这个问题, 请问有什么解决方法吗?

**Comment by 1993hzw** [comment]
我在虚拟机上并没有出现卡顿问题

**Comment by 1993hzw** [comment]
我在虚拟机上测试没有出现这个问题。你有做什么改动吗？你的机型是什么？

**Comment by ReisenZ** [comment]
整个demo没有进行任何改动, 我在虚拟机上也没有复现这个问题. 目前仅在华为c5的pad上出现这个问题, 我会联系厂商看是否是厂家的bug




 
发件人： hzw
发送时间： 2018-10-22 14:06
收件人： 1993hzw/Doodle
抄送： Reisen; Author
主题： Re: [1993hzw/Doodle] Android8.0设备上图片旋转后继续涂鸦卡顿 (#3)
我在虚拟机上测试没有出现这个问题。你有做什么改动吗？你的机型是什么？

**Comment by ReisenZ** [comment]
这个bug基本确定是厂家rom的问题...已经联系厂家处理这个问题了
