### ISSUE TITLE
如何限制图片拖动的范围

### ISSUE THREAD

**Issue by DaneChen** [1993hzw/Doodle#35]
你好，我把mMinScale设置成了1，在编辑模式下，如果没有mSelectedItem，可以拖动图片到手机屏幕外，然后会有动画弹回来。问下能不能限制这个拖动？

我尝试，在DoodleOnTouchGestureListener类的onScroll方法中，注释掉 mDoodle.setDoodleTranslation调用，发现放大后也不能移动了，是不是在这里判断滑动的偏移就可以？我经常把这些坐标关系搞混..麻烦作者帮忙分析个思路

非常感谢这个强大的库orz

**Comment by 1993hzw** [comment]
最新代码加入了编辑模式哦，只有编辑模式下才能移动图片
