### ISSUE TITLE
为什么要额外的引用一个依赖啊

### ISSUE THREAD

**Issue by MaleWxt** [1993hzw/Doodle#42]
api 'com.github.1993hzw:Androids:1.3'

**Comment by sweet-guy** [comment]
ERROR: Unable to resolve dependency for ':doodle@debug/compileClasspath': Could not resolve com.github.1993hzw:Androids:1.3. 这个导不进去？

**Comment by MaleWxt** [comment]
> ERROR: Unable to resolve dependency for ':doodle@debug/compileClasspath': Could not resolve com.github.1993hzw:Androids:1.3. 这个导不进去？

是的，依赖无法下载下来，感谢您的回复。

**Comment by sweet-guy** [comment]
我也是遇到这个问题，还没有解决。

**Comment by 1993hzw** [comment]
加上配置了吗?
`allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}`

**Comment by sweet-guy** [comment]
依赖jitpack后不行，我把androids 工程model放进去可以了，建议作者把androids里用到的几个控件放到Doodle中，这个图片编辑功能很全，正好用到。

**Comment by sweet-guy** [comment]
提个建议，再加个改变笔的颜色，可以自定义选择ui，感觉就更完美了。最后向大佬鞠躬！

**Comment by MaleWxt** [comment]
> 提个建议，再加个改变笔的颜色，可以自定义选择ui，感觉就更完美了。最后向大佬鞠躬！

是的，我是觉得大佬这东西做得真心不错，就是自定义ui这块有点欠缺，目前我是想想更改添加文字的时候，文字的背景框，能在左上角增加一个删除的X类似的，看了代码发现不是很好处理这块。

**Comment by 1993hzw** [comment]
感谢建议，后续会考虑哦。
