### ISSUE TITLE
这个图橡皮檫 无效果 大佬帮忙看一下

### ISSUE THREAD

**Issue by sweet-guy** [1993hzw/Doodle#43]
![avatar](https://img-blog.csdnimg.cn/20200326112117612.png)

**Comment by sweet-guy** [comment]
看到代码有注释透明度可能无法擦除，想请教一下有啥好的解决方案么

**Comment by 1993hzw** [comment]
传入一张白色图片,保存后为什么会变成黑色呢/

**Comment by sweet-guy** [comment]
> 传入一张白色图片,保存后为什么会变成黑色呢/

因为白色图片Android 会认为是透明图片，图片加载就会变成黑色背景，我尝试把背景颜色矩阵遍历变为白色，但是效果还是黑色

**Comment by 1993hzw** [comment]
怎么可能会把白色图片当做透明图片呢?你看看哪里搞错了.
