### ISSUE TITLE
添加Text的UI能自定义吗？输入的文本要能自动换行该怎么做？

### ISSUE THREAD

**Issue by kofihust** [1993hzw/Doodle#44]
<img width="207" alt="企业微信截图_15857544846916" src="https://user-images.githubusercontent.com/9524120/78155038-8c2a5d80-746f-11ea-805a-6945813f39ec.png">
1.添加Text的UI我想做成图中这种样式，虚线框到还好，右上角一个×的图标还要带click事件不太好搞；
2.输入的文本只能是一行，要是文本太长超出范围就截断了，想做到自动换行该怎么做？

**Comment by 1993hzw** [comment]
1. 自定义UI只能通过复写或继承DoodleText.doDraw
2.  绘制文本时可以通过StaticLayout进行换行处理。
