### ISSUE TITLE
第一次加载显示大图，然后大图不能滑动了，怎么回事

### ISSUE THREAD

**Issue by wuh876** [1993hzw/Doodle#48]
第一次加载显示大图，然后大图不能滑动了，怎么回事？
怎么在图片边缘外绘制文字，现在绘制的再图片上显示不全

**Comment by 1993hzw** [comment]
先用demo跑是否有问题，如果没有问题在对比项目中的使用差异。
目前画布大小跟图片大小是一致的，超出范围外的均不显示。
