### ISSUE TITLE
怎么在图片外面涂鸦

### ISSUE THREAD

**Issue by wuh876** [1993hzw/Doodle#49]

**Comment by 1993hzw** [comment]
现在的有效涂鸦范围是跟图片大小一样的

**Comment by wuh876** [comment]
如果点在图片边上的添加文字会显示不全？

**Comment by sunpan3213** [comment]
改源码啊,我已经在改了,把clip的代码修改下

**Comment by wuh876** [comment]
不会改

**Comment by sunpan3213** [comment]
额,等我改好了再说

**Comment by wuh876** [comment]
嗯，我是在另一个画布上画的

**Comment by sunpan3213** [comment]
啥意思，自己从0开始写？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wuh876 <notifications@github.com&gt;
发送时间: 2020年12月31日 11:58
收件人: 1993hzw/Doodle <Doodle@noreply.github.com&gt;
抄送: panda <1046633430@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[1993hzw/Doodle] 怎么在图片外面涂鸦 (#49)





 
嗯，我是在另一个画布上画的

**Comment by sunpan3213** [comment]
> 嗯，我是在另一个画布上画的

现在搞好没

**Comment by 1993hzw** [comment]
目前画布大小是跟图片大小保持一致的，超出范围的将不会绘制。
