### ISSUE TITLE
长按事件

### ISSUE THREAD

**Issue by wuh876** [1993hzw/Doodle#50]
@Override
 public void onLongPress(MotionEvent e) {
}

这个事件怎么不执行呢

**Comment by 1993hzw** [comment]
具体你是怎么监听的呢

**Comment by wuh876** [comment]
mTouchGestureListener = new DoodleOnTouchGestureListener(mDoodleView,
                    new DoodleOnTouchGestureListener.ISelectionListener() {
                        @Override
                        public void onSelectedItem(IDoodle doodle, IDoodleSelectableItem selectableItem, boolean selected) {
                        }

                        @Override
                        public void onCreateSelectableItem(IDoodle doodle, float x, float y) {
                      
                        }
                    }) {
                @Override
                public boolean onDoubleTap(MotionEvent e) {
 return super.onDoubleTap(e);
                }

                @Override
                public void onLongPress(MotionEvent e) {
              
                }

            };

**Comment by 1993hzw** [comment]
在DoodleTouchDetector里禁掉了长按事件, `setIsLongpressEnabled(false)`. 因为这个交互跟其他交互有冲突

**Comment by wuh876** [comment]
谢谢
