### ISSUE TITLE
开启绘制优化之后会有很大概率崩溃

### ISSUE THREAD

**Issue by liumqi** [1993hzw/Doodle#52]
private void initDoodleBitmap() {
        ...
        if (mDoodleBitmap != null) {
            mDoodleBitmap.recycle();
        }
    }
private void doDraw(Canvas canvas) {
           ...
            Bitmap bitmap = mOptimizeDrawing ? mDoodleBitmap : mBitmap;
        }

保存图片时会先调用initDoodleBitmap()此时mDoodleBitmap 销毁，但是在doDraw()方法会用到这个bitmap对象，此时就会抛异常然后程序崩溃，有什么好的处理方法吗？谢谢

**Comment by 1993hzw** [comment]
/**
     * called when save the doodled iamge. 保存涂鸦图像时调用
     *
     * @param doodle
     * @param doodleBitmap       涂鸦后的图片
     * @param callback  called after saving the bitmap, if you continue to doodle. 保存后的回调，如果需要继续涂鸦，必须调用该回调
     */
    void onSaved(IDoodle doodle, Bitmap doodleBitmap, Runnable callback);

如果想继续涂鸦, 保存后请调用 callback.run()
