### ISSUE TITLE
橡皮擦擦除的内容

### ISSUE THREAD

**Issue by JunWeiAndroid** [1993hzw/Doodle#55]
你好，我现在在使用这个库，有一个需求是，橡皮擦擦除时只擦除涂鸦的内容，不能擦除添加的文字、图片等元素。请问这个能实现么，或者有没有什么思路。谢谢

**Comment by 1993hzw** [comment]
目前橡皮擦的原理是把原图作为画笔底图进行覆盖绘制，跟涂鸦一样，所以要实现你的需求，必须把橡皮擦绘制在涂鸦之上，其他内容之下，这样才不会遮住其他内容。
