### ISSUE TITLE
如果位图包含透明度，则可能会导致橡皮擦无法对透明部分进行擦除

### ISSUE THREAD

**Issue by kerry202** [1993hzw/Doodle#56]
这个问题有办法解决吗？我尝试了修改画笔颜色为#00000000 完全透明。结果行不通

**Comment by yb801925** [comment]
新建一个橡皮擦paint --- 可以解决

**Comment by 1993hzw** [comment]
目前橡皮擦的原理是把原图作为底图进行绘制覆盖，因此如果原图包含透明度，那么橡皮擦也会包含透明度。
