### ISSUE TITLE
Canvas: trying to draw too large(106010920bytes) bitmap.

### ISSUE THREAD

**Issue by wuh876** [1993hzw/Doodle#61]
![微信截图_20210126102654](https://user-images.githubusercontent.com/17919150/105791467-1f192300-5fc1-11eb-886b-c00952fe4ec2.png)

**Comment by oOJohn6Oo** [comment]
你是不是想在类似`ScrollView`这样可滚动的View上涂鸦。

**Comment by wuh876** [comment]
不是，就是一张图上，我用bitmapfactory.decodefile之后图片就变大了

**Comment by 1993hzw** [comment]
解析图片获取bitmap时建议进行压缩，避免大图导致OOM
