### ISSUE TITLE
很想用你这个项目，但是你用的compile 'com.github.1993hzw:Androids:1.2.3'我本地死都下载不下来

### ISSUE THREAD

**Issue by liunian1010** [1993hzw/Doodle#7]
很想用你这个项目，但是你用的compile 'com.github.1993hzw:Androids:1.2.3'我本地死都下载不下来

**Comment by 1993hzw** [comment]
看文档使用说明呀！加上maven地址
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
 
dependencies {
    compile 'com.github.1993hzw:Doodle:5.3'
}
