### ISSUE TITLE
如何判断在图片区域外黑色背景上涂鸦？？

### ISSUE THREAD

**Issue by xuehuashi** [1993hzw/Doodle#8]
RectF picBound = mDoodle.getDoodleBound();  图片在画布上的矩形区域？？  滑动的时候：Boolean containPoint = picBound.contains(mDoodle.toX(((mTouchX + mLastTouchX) / 2)), mDoodle.toY((mTouchY + mLastTouchY) / 2));   把屏幕触摸点映射到图片上，去判断是否在图片区域外黑色背景色涂鸦，可以吗？ 目的是实现 只要有一个点在图片上，撤销按钮就可点击，否则在黑色区区涂鸦不可点击

我测试一些图片宽大于高，背景区域涂鸦轨迹也加入撤销栈中了。

**Comment by 1993hzw** [comment]
如下解释，不需要调用toX,toY进行转换
/**
     * 获取当前图片在View坐标系中的矩型区域
     *
     * @return
     */
    public RectF getDoodleBound()

**Comment by xuehuashi** [comment]
thanks,我在doodleontouchgesturelisten类onscroll 方法中加入，
Rect bounds = mDoodle.getCanvas().getClipBounds();
 containPoint = bounds.contains((int) mDoodle.toX(mTouchX), (int) mDoodle.toY(mTouchY));
 if (containPoint) {
      mDoodle.addItem(mCurrDoodlePath);
}  也实现了效果，不晓得对不对
