### ISSUE TITLE
放大图片后，  画笔涂鸦怎么保持画笔的大小不被缩放？

### ISSUE THREAD

**Issue by xuehuashi** [1993hzw/Doodle#9]

**Comment by 1993hzw** [comment]
[参考＂不跟随缩放变化的文字item＂](https://github.com/1993hzw/Doodle/blob/master/extend.md)

**Comment by threedeer** [comment]
你好，你这个不跟随缩放，centerCrop()   这个方法怎么使用的呢？
我新增并使用了FixedSizeDoodleText之后字体大小依然是跟随图片的缩放而缩放了
